[package]
name = "cost-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.18.11"
solana-sdk = "1.18.11"
spl-token = "4.0.0"